kind: Service
apiVersion: v1
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: todo-service
spec:
  type: LoadBalancer
  selector:
    app: todo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090